### ISSUE TITLE
Option to not send timings in case of an exception

### ISSUE THREAD

**Issue by zeebonk** [jsocol/pystatsd#123]
The timing decorator is a very concise way of logging timing information for a block of code. We use these timings as the input for SLIs in our platform. When an exception takes places inside a timing context manager, the timing is always send. In our situation it would be preferable to NOT send a timing in case of an Exception.

Would you be open for a PR that adds an extra optional argument to the `Timer` class that disables sending timings in case of an exception? For example: `log_on_exception=True`? The reason I'm asking is because it seems like a strange argument to have if you use the `Timer` class without the context manager.

Or, if the above is not something you'd want, perhaps you might have other ideas for supporting this? I'm open for doing the implementation!

**Comment by jsocol** [comment]
Hmm, is that going to provide much extra value over [this form of timers](https://statsd.readthedocs.io/en/v3.3/timing.html#using-a-timer-object-directly)?

```py
timer = statsd.timer('my_stat_name')
timer.start()
some_expensive_op()
timer.stop() # not called on exception
```

To me, the whole reason to pay the cost of indenting further with the context manager is to get the timing _no matter what_. Otherwise, there's a flatter option, as above.

`.start()` and `.stop()` also return `self` so they can be chained, e.g.

```py
timer = statsd.timer('my_stat').start()
something_slow()
timer.stop()
```

**Comment by zeebonk** [comment]
@jsocol I like the 'no matter what' idea. I'm just going to use your suggested method. Thanks!
