### ISSUE TITLE
Statsd binds to all interfaces this is a security concern

### ISSUE THREAD

**Issue by devosalain** [jsocol/pystatsd#147]
Feature request,
Allow statsd to bind to a certain interface or IP-address.

sockstat -46L returns:
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS      
root     python3.8  89566 3  udp4   *:randomport               *:*
I prefer : 127.0.0.1:randomport as I run on a public interface.

**Comment by devosalain** [comment]
Python statsd is currently unsuable to me as I sit on a public interface.
It's a pitty because otherwise it is a nice program.

**Comment by kapilt** [comment]
this repo represents a client not a server, aka its not listening on a socket.

**Comment by jsocol** [comment]
> this repo represents a client not a server, aka its not listening on a socket.

For UDP (and I think all Python sockets, but I'd have to double check) the client is still opening a socket to listen to replies. (StatsD doesn't send any, as far as I know, but bidirectional UDP is a valid use case.)

@devosalain I'm not even sure how to configure this behavior since it's the automatically-created listener. I'm happy to look at a PR if you know how to adjust this.

**Comment by jsocol** [comment]
I looked at the `socket` docs and wasn't able to find a way to control this behavior. It's entirely possible I missed something, though, so if anyone is aware of a way to control which interface an outgoing socket uses, feel free to re-open or create a PR.
