### ISSUE TITLE
package not updated on pypi anymore

### ISSUE THREAD

**Issue by puppetninja** [jsocol/pystatsd#152]
Hi,
it looks like statsd has been updated on pypi since 2018
https://pypi.org/project/statsd/#description
would appreciate if latest statsd could be installed via pip

**Comment by jsocol** [comment]
The statsd protocol hasn’t changed and so this client hasn’t needed to change much. There is one small feature that’s been added and otherwise just testing on newer and newer versions of Python. 

Probably there will be a 4.0 soonish that drops support for Python 2 completely and May add async interfaces, but beyond that there still isn’t much to do here.
