### ISSUE TITLE
Noop client if a connection is not available

### ISSUE THREAD

**Issue by miracle2k** [jsocol/pystatsd#39]
My could sometimes needs to run in scenarios where a statsd host is not available. I don't want to wrap every call to statsd into a condition.

statsd seems to be behave well if just using an empty string as the host, but I can't help but worry that this is the wrong thing performance wise.

Is it a bad idea to just fire-and-forget and not worry about a statsd server being there? What is the right way?

**Comment by ishansgupta** [comment]
Coming back to this, I am wondering whats the best way to use a Noop client in case a connection fails. Using a "" host doesn't seem to do the trick. I

**Comment by jsocol** [comment]
Hey @ishansgupta. I think this has probably changed in the past 7 years. The client now—since a long time ago but I don't know exactly when—tries to do a proactive DNS lookup to avoid adding DNS overhead to every call. Setting the host to `"localhost"` in dev or test environments should probably work. It still swallows all transmission errors.
