### ISSUE TITLE
Timer decorators on multiple functions send the same time values

### ISSUE THREAD

**Issue by sjwk** [jsocol/pystatsd#58]
This might be a bug, or by design and just my understanding of the docs that's bugged:

I have a script (just a single thread) that is using decorators to apply timers to various functions so that I can see how long is spent in those functions on each run.
However it seems that all timers, despite being different instances with different names, all send the same time value. (On my script, some functions take several seconds to run, yet all statsd timer values were showing up as around 66ms)

For example, a test script to demonstrate this:
```python
import time
import statsd

sd=statsd.StatsClient('statsdhost', 8125, prefix='test')

@sd.timer('wait_1')
@sd.timer('wait_2')

def wait_1():
        time.sleep(1)

def wait_2():
        time.sleep(10)

wait_2()
wait_1()
with sd.timer('test2'):
        wait_2()
```
sends the following values (captured from tcpdump between the machine the script is running on and the statsd host):
```
test.wait_2:1001|ms
test.wait_1:1002|ms
test.test2:10010|ms
```
The values aren't quite the same (1001 vs 1002), so it presumably isn't just using the same timer value, but test.wait_2 clearly isn't ~10,000ms either.  Changing the order that wait_1 and wait_2 are called does not change the value that is sent for both functions.

So, is this an issue, or is it my understanding of the code, and you can simply only have one timer running on a decorated function?  The docs don't say you can have more than one, but they don't say you can't either!

**Comment by jsocol** [comment]
The tcpdump output here looks exactly correct to me. Where did the 66ms come from?

```python
@sd.timer('wait_1')
@sd.timer('wait_2')

def wait_1():
        time.sleep(1)
```

This decorates the function `wait_1` with two timers. The "inner" one is `test.wait_2`, so it completes first, then `test.wait_1` finishes. (That's why `test.wait_2` is 1001ms and `test.wait_1` is 1002ms.)

The function `wait_2` sleeps for 10s, and is not decorated at all, so

```python
wait_2()
wait_1()
```

causes the script to sleep for 10s, reporting nothing, then sleep for 1s and report two timers. Then finally

```python
with sd.timer('test2'):
        wait_2()
```

sleeps for 10 seconds within a timed block, and submits `test.test2` with a value of ~10s.

If you want to decorate the `wait_2` function, you'd need to do something like this:

```python
@sd.timer('wait_1')
def wait_1():
    time.sleep(1)

@sd.timer('wait_2')
def wait_2():
    time.sleep(10)
```

**Comment by sjwk** [comment]
the 66ms was what I was getting from all functions in my real world script.

OK, I understand now - it was my understanding that was broken - i.e., I assumed that the `@sd.timer()` definitions were just defining (at the top of the script) all of the decorators and the functions that they applied to - not that they then all applied to the first function and the rest of the functions had no timers attached...

Many thanks for clearing that up!
