### ISSUE TITLE
Backpoff mode for TCP client

### ISSUE THREAD

**Issue by mlowicki** [jsocol/pystatsd#80]
Right now when StatsD is down `TCPStatsClient` will try to establish TCP connection while handling each metric which is definitely unnecessary when it goes to use of resources and network saturation.

Idea is to either implement simple logic like wait 1 second between each re-try or make it pluggable so would be easy to implement f.ex. exponential backoff.

**Comment by jsocol** [comment]
With TCPStatsClient the intent is that it's up to the managing application to decide how to handle sending failures. That's why there is no exception handling around the `_sock.sendall` call.

That's not quite what will happen. A closed `socket.socket` object is [still truthy](https://github.com/jsocol/pystatsd/blob/master/statsd/client.py#L172-L173), so it won't automatically try to reconnect here:

```python
    def _send(self, data):
        """Send data to statsd."""
        if not self._sock:
            self.connect()
        self._do_send(data)
```

it'll just fail. (It'll only try to connect if it's never been connected.) The application can decide to call `TCPStatsClient.reconnect` and retry, or else catch and log the failure, or let the error bubble up, or whatever.

In general, if you don't need to know reliably that a packet was sent, use the regular (UDP) StatsClient (it's much much faster). If you do need to know and react somehow, use TCPStatsClient, but it's not going to have an opinion on the right way for the application to handle the failure.

**Comment by mlowicki** [comment]
Scenario we've found it that when application is started (after release) and StatsD server is down (we still need TCP) then `self._socket` will be always None if it couldn't establish connection at least once.
