### ISSUE TITLE
Asyncio support

### ISSUE THREAD

**Issue by povilasb** [jsocol/pystatsd#93]
I hope motivation is clear - I want to send metrics from my async daemon :)

TCP transport implementation looks very lean https://github.com/jsocol/pystatsd/blob/master/statsd/client.py#L157.
So I guess it would not be too hard to implement asyncio support.

Maybe I could even do it on my spare time.
What do you guys think?

**Comment by jsocol** [comment]
What kind of API do you imagine for asyncio? Would it be breaking or backwards compatible?

**Comment by povilasb** [comment]
It would definitely be backwards compatible.
We could introduce new class that explicitly states that it's intended to be used with `asyncio`.
E.g.:
```python
class AsyncStatsClientBase:
    def __init__(self, loop):
        pass

    async def incr(self, stat, count=1, rate=1):
         await self._send_stat(stat, '%0.6f|ms' % delta, rate)

    async def decr(self, stat, count=1, rate=1):
        pass

    # ...
```

Or maybe we could even name it more specifically `class AsyncioStatsClientBase`.
Thus allow supporting other async loops:
* https://github.com/dabeaz/curio
* twisted
* etc.

**Comment by jsocol** [comment]
Hmm, that would need to be in a completely separate module, since it can't be imported in Py2 or older Py3. It's not clear how it would work with the `defaults` module, and it's also going to double the API surface area. How would the tests run on Py2, since it's a syntax error?

Anything that doubles the surface area makes me wonder if there should be a fork, e.g. `statsd-asyncio`, to serve the need better.

**Comment by povilasb** [comment]
Well we could detect python version and define asyncio compatible code only for specific versions, e.g.:
```python
if PY_35:
    class AsyncStatsClient:
        pass
```
Where `PY_35` is https://github.com/aio-libs/aiohttp/blob/master/aiohttp/abc.py#L7.

Or maybe it's not worth the hassle. Recently I found https://lab.errorist.xyz/abc/aiomeasures

**Comment by jsocol** [comment]
Is `@asyncio.coroutine` equivalent to using the `async / await` keywords? There are a couple of issues to work around:

1. Those keywords are a syntax error in older versions, so you can't import or define code that uses them at all into Py<=3.4-compatible modules.
2. If you need to add `async / await` or `@types.coroutine / yield from` to every method, you'll need a second copy of every method of every implementation (i.e. "doubles the surface area") that's the same interface, but async.
3. Even if you could find a way to avoid doing that, implicit behavior changes are bad: there _should_ be an `AsyncStatsClient` and `AsyncTCPStatsClient` and...

You should have to deliberately opt into the async interface—nothing should suddenly change behavior unexpectedly. That means async-enabled versions of every existing interface—but they have to be imported from somewhere distinct because they can't reliably be imported into Py2-compatible modules. And is there a strong reason to have `from statsd.async import AsyncStatsClient` instead of `from statsd_async import AsyncStatsClient`?

**Comment by povilasb** [comment]
Well, in such case there's already https://pypi.python.org/pypi/aiomeasures.
Should we close the case?

**Comment by jsocol** [comment]
Yeah, I'm going to close this, but thanks for filing it! Now we have a good place to point people looking for asyncio support.
